### ISSUE TITLE
Add Spell Scaling

### ISSUE THREAD

**Issue by StivThe8thDwarf** [ThomasJClark/elden-ring-weapon-calculator#9] opened 2023-04-23 18:26 UTC
Add Spell Scaling for catalyst, right now it shows only the effective AR, not the Spell Scaling. I know that there is already a tool made for this, but it doesn't include Elden Ring Reforged. May be usefull, since you are covering ERR AR, to include Spell Scaling too.

**Comment by ThomasJClark** [comment] 2023-04-23 18:44
Good point. I've held off on adding spell scaling because [the jerp tool](https://jerp.tv/eldenring/spelltools/) is already really good for vanilla, but Elden Ring Reforged support might be a good enough reason to add support

**Comment by StivThe8thDwarf** [comment] 2023-04-24 12:52
The Spell Scaling is not accurate. They changed the Scaling of some catalyst. For example, Prince of Death's Staff scales S/S/S INT/FAI/S at +25, not B/B/A. Scepter of the All-Knowing is A/A/S, not B/B/A.

**Comment by ThomasJClark** [comment] 2023-04-24 16:39
Thanks for the heads up, that's probably because calculator is still based on ERR v0.6.5B. Some people on the discord mentioned v0.6.6A changed some weapon scaling, and it's possible that spell scaling was also adjusted

ivi is helping me figure out the best way to stay up to date in the long term (see #11) but in the short term I can manually apply the v0.6.6A update later today.

**Comment by ThomasJClark** [comment] 2023-04-25 03:49
I updated the app to ERR v0.6.6A, and confirmed that spell scaling and attack power calculations for a few examples are correct. However, the scaling for the staff still incorrectly displays as A/A/A in the calculator.

@ividyon does the mod change anything about how the letter scaling is displayed? It looks like PoDS +25 should have 150 scaling in int/fai/arc which corresponds to A in the vanilla game, but it shows S in the mod.

![image](https://user-images.githubusercontent.com/3964980/234169744-d323e8b2-7011-40cb-b934-e3d0b4e703ec.png)

![image](https://user-images.githubusercontent.com/3964980/234169684-8a42ca80-767f-436b-91b7-5a5d80b2d2be.png)

**Comment by ividyon** [comment] 2023-04-25 06:50
@ThomasJClark The letters that correspond to the correct numbers are determined in MenuValueTableParam. Type 1 is used for scaling.

**Comment by ThomasJClark** [comment] 2023-04-26 02:43
Thanks, exactly what I was looking for. Fixed in #14.

**Comment by StivThe8thDwarf** [comment] 2023-04-26 07:41
I think that there's still something wrong. PoDS only states 184 total Attack Power, but it should be way higer. The scaling displayed is correct, the numerical value of the attack power is not.

**Comment by ThomasJClark** [comment] 2023-04-29 22:30
@StivThe8thDwarf looking into this now

Are you looking at the live app ([eldenring.tclark.io](https://eldenring.tclark.io)) or the spell scaling preview app ([spellscaling.elden-ring-weapon-calculator.pages.dev](https://spellscaling.elden-ring-weapon-calculator.pages.dev/))? 184 seems correct for AP while the Spell Scaling should be 369, but the live version currently doesn't have spell scaling yet.

![image](https://user-images.githubusercontent.com/3964980/235326330-c578919c-fdda-428b-86ac-949e492d74ef.png)

![image](https://user-images.githubusercontent.com/3964980/235326413-5d948493-c762-4eb1-b697-ddbb7de25695.png)

**Closed** 2023-04-30 02:31 UTC
